name: reciteme_spacex
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  http: ^1.1.2
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  carousel_slider: ^4.2.1
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  path: ^1.8.3
  injectable: ^2.3.2
  dio: ^5.3.4
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  injectable_generator:
  flutter_launcher_icons: ^0.13.1


flutter_native_splash:
  image: assets/images/logo.png
  color: "#1D205D"
  color_dark: "#1D205D"
  image_dark: assets/images/logo.png
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#1D205D"
    theme_color: "#1D205D"
  macos:
    generate: true
    image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
